package parser

import (
	"fmt"

	"github.com/stream-enterer/go2kdl/document"
	"github.com/stream-enterer/go2kdl/internal/tokenizer"
)

type Parser struct {
}

// New creates a new Parser
func New() *Parser {
	return &Parser{}
}

// NewContext creates a new ParseContext
func (p *Parser) NewContext() *ParseContext {
	return p.NewContextOptions(defaultParseContextOptions)
}

func (p *Parser) NewContextOptions(opts ParseContextOptions) *ParseContext {
	return &ParseContext{
		doc:  document.New(),
		opts: opts,
	}
}

var eofToken = tokenizer.Token{
	ID:   tokenizer.EOF,
	Data: []byte{},
}

func (p *Parser) annotatedError(err error, t tokenizer.Token, _ []tokenizer.Token, _ int, source []byte) error {
	return &ParseError{
		Message: err.Error(),
		Line:    t.Line + 1,
		Column:  t.Column + 1,
		Offset:  t.Offset,
		Length:  len(t.Data),
		Source:  source,
	}
}

// Parse parses a single token (usually generated by tokenizer.Scanner) into the given context, and returns a non-nil
// error on failure
func (p *Parser) parse(c *ParseContext, token tokenizer.Token) error {
	if c.continuation {
		switch token.ID {
		case tokenizer.Whitespace, tokenizer.MultiLineComment:
			// continue waiting for the first token of the next (continued) line
		case tokenizer.Newline:
			// consume the newline and clear continuation; subsequent newlines will
			// be handled normally (terminating the current node, etc.)
			c.continuation = false
			return nil
		case tokenizer.SingleLineComment:
			// a single-line comment consumes the rest of the line; keep
			// continuation active so the following newline is also consumed
		default:
			// this is the first token of the next (continued) line
			c.continuation = false
		}
	}

	validTransitions := stateTransitions[c.state]

	handler, ok := validTransitions[token.ID]
	if !ok {
		// if there's no handler for this token's specific ID, check for a handler for the class of token instead
		tokenClasses := token.ID.Classes()
		for _, tokenClass := range tokenClasses {
			if handler, ok = validTransitions[tokenClass]; ok {
				break
			}
		}
	}

	var err error
	if handler == nil {
		err = fmt.Errorf("unexpected %s in state %s", token.ID, c.state)
	} else {
		err = handler(c, token)
	}

	return err
}

func (p *Parser) Parse(c *ParseContext, token tokenizer.Token) error {
	c.recent.Add(token)
	if err := p.parse(c, token); err != nil {
		tokens := c.recent.Get()
		return p.annotatedError(err, token, tokens, len(tokens)-1, c.source)
	}

	return nil
}

// ParseAll parses a slice of tokens and returns the resulting Document, or a non-nil error on failure
func (p *Parser) ParseAll(tokens []tokenizer.Token) (*document.Document, error) {
	c := p.NewContext()
	return p.ParseAllContext(c, tokens)
}

// ParseAllContext parses a slice of tokens using the given context and returns the resulting Document, or a non-nil
// error on failure
func (p *Parser) ParseAllContext(c *ParseContext, tokens []tokenizer.Token) (*document.Document, error) {
	for i, t := range tokens {
		if err := p.Parse(c, t); err != nil {
			return nil, p.annotatedError(err, t, tokens, i, c.source)
		}
	}

	eof := eofToken

	if len(tokens) > 0 {
		lastToken := tokens[len(tokens)-1]
		eof.Line = lastToken.Line
		eof.Column = lastToken.Column + len(lastToken.Data)
	}

	if err := p.Parse(c, eof); err != nil {
		return nil, p.annotatedError(err, eof, tokens, len(tokens)-1, c.source)
	}

	return c.doc, nil
}
